### ISSUE TITLE
old fashioned error

### ISSUE THREAD

**Issue by benyomin** [lmullen/bibkeys#1]
How can I work around this?  Error when calling from bash: 

     bibkeys backupBibFile.bib
       2.3.0/gems/bibtex-ruby-2.3.4/lib/bibtex/bibliography.rb:121: 
       warning: BibTeX::Entry#respond_to?(:to_ary) is old fashion which 
       takes only one parameter

 #begin pseudo code

    require 'bibtex'
    require 'bibkeys'
    b = BibTeX.open('./ruby.bib')
    for |key| in b
    puts "file = {'./mydir/pdfs/%key.pdf'}"
    b.save

**Comment by lmullen** [comment]
This software is no longer supported. I've updated the README to reflect that. Your best bet is to take a look at the bibtex-ruby gem, which did the actual heavy lifting.
